dependencies:
  pre: 
    - sudo apt-get update; sudo apt-get install redis-server -y

machine:
  ruby:
    version: ruby-2.3.1

test:
  post:
    - rackup faye.ru -s thin -E production
    - redis-server